services:
  app:
    image: banking-app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_ENV: ${SERVER_ENV}
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  app-db:
    external: true
